accounts/urls.py
"""Urls used in the accounts app."""
from django.urls import include, path

from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.routers import DefaultRouter

from .views import (
    _LoginView,
    _LogoutView,
    CompanyListView,
    CompanyCreateView,
    CompanyUpdateView,
    AddressListView,
    AddressCreateView,
    AddressUpdateView,
    CompanyViewSet,
    AddressListAPIView,
    ObtainExpiringAuthToken,
)

app_name = 'accounts'

urlpatterns = [
    path(
        'login/',
        _LoginView.as_view(
            template_name='accounts/login.html',
            extra_context={'login_active': 'active'}
            ),
        name='login'
        ),
    path('logout/', _LogoutView.as_view(next_page='core:home'), name='logout'),
    path('companies/', CompanyListView.as_view(), name='companies'),
    path('companies/add/', CompanyCreateView.as_view(), name='company_add'),
    path(
        'companies/<int:number>/',
        CompanyUpdateView.as_view(),
        name='company_update'
        ),
    path(
        'companies/<int:number>/addresses/',
        AddressListView.as_view(),
        name='company_addresses'
        ),
    path(
        'companies/<int:number>/address/add/',
        AddressCreateView.as_view(),
        name='company_address_add'
        ),
    path(
        'companies/<int:number>/address/<int:pk>/',
        AddressUpdateView.as_view(),
        name='company_address_update'
        ),
]

router = DefaultRouter(trailing_slash=False)
router.register(r'api/companies', CompanyViewSet)

api_viewsets = [
    path('', include(router.urls)),
    ]
api_urlpatterns = format_suffix_patterns([
    path(
        'api/companies/<slug:number>/addresses',
        AddressListAPIView.as_view(),
        name='api-company_addresses'
        ),
    path('api/token', ObtainExpiringAuthToken.as_view(), name='api-get_token'),
])

urlpatterns.extend(api_viewsets)
urlpatterns.extend(api_urlpatterns)

core/urls.py
from django.urls import path

from .views import Homepage

app_name = 'core'

urlpatterns = [
    path('', Homepage.as_view(), name="home"),
]

accounts/forms.py
"""functionality for account forms."""
from django import forms
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _

from core.forms import AbstractModelForm, AuditableFormMixin

from . import TYPE_MAIN
from .models import Profile, Company, Address


class AddressForm(AuditableFormMixin):
    """Address form."""

    def __init__(self, *args, **kwargs):
        """Get a company or a profile to use in the Address."""
        number = kwargs.pop('number', None)
        username = kwargs.pop('username', None)
        super().__init__(*args, **kwargs)
        if number:
            self.company = Company.objects.get(number=number)
        elif username:
            self.profile = Profile.objects.get(username=username)

    def clean(self):
        """Ensure that there is only one main type.

        Note that if there is no address, then we have to create it. Otherwise,
        creation will fail.
        """
        cleaned_data = super().clean()
        has_main = self.company.addresses.filter(
            type=TYPE_MAIN,
            is_active=True
            )
        has_main = has_main.filter(~Q(id=self.instance.id))
        if cleaned_data.get('is_active') and \
           has_main and \
           cleaned_data.get('type') == TYPE_MAIN:
            raise forms.ValidationError(_(
                "Cannot have more than one Main Address."
            ))
        # get or create addresses for a model
        if not self.instance.id:
            if self.company:
                self.company.addresses.create(
                    **cleaned_data,
                    modified_by=self.profile
                    )
            elif self.profile:
                self.profile.addresses.create(
                    **cleaned_data,
                    modified_by=self.profile
                    )
        return cleaned_data

    class Meta:
        """Class Meta."""

        model = Address
        exclude = [
            'country',
            'company',
            'modified_by',
            'profile',
            'content_type',
            'object_id'
        ]


class ActorFormMixin(AbstractModelForm):
    """Actor Form. Deprecated?."""

    actor_type = forms.CharField(label=_('Actor Type'), max_length=8)

    def __init__(self, *args, **kwargs):
        """Set initial data for an actor form."""
        is_provider = kwargs.pop('provider', False)
        is_renter = kwargs.pop('renter', False)
        is_buyer = kwargs.pop('buyer', False)
        super().__init__(*args, **kwargs)
        renter_field = self.fields.get('is_renter')
        provider_field = self.fields.get('is_provider')
        buyer_field = self.fields.get('is_buyer')
        actor_type = self.fields.get('actor_type')
        if not renter_field and not provider_field and not buyer_field:
            raise AttributeError(
                _('Actor form must have "Actor Type" fields.')
                )
        renter_field.required = is_renter
        provider_field.required = is_provider
        buyer_field.required = is_buyer
        actor_type.initial = self._meta.model.get_actor_type(self.instance)
        renter_field.widget = forms.widgets.HiddenInput() if\
            not renter_field.required else renter_field.widget
        provider_field.widget = forms.widgets.HiddenInput() if\
            not provider_field.required else provider_field.widget
        buyer_field.widget = forms.widgets.HiddenInput() if\
            not buyer_field.required else buyer_field.widget


class CompanyForm(AuditableFormMixin):
    """A Form for the Company model."""

    def clean(self):
        """Ensure that there is a provider, renter or buyer."""
        cleaned_data = super().clean()
        errors = []
        if not cleaned_data.get('is_provider', False) and\
           not cleaned_data.get('is_renter', False) and\
           not cleaned_data.get('is_buyer', False):
            errors.append(forms.ValidationError(
                _('A Company must have a Type (Provider, Renter or Buyer).')
            ))
        if errors:
            raise forms.ValidationError(errors)
        return cleaned_data

    def clean_number(self):
        """Ensure that the number is bigger than min_chars."""
        number = self.cleaned_data.get('number')
        min_chars = 11
        if len(str(number)) < min_chars:
            raise forms.ValidationError(
                _('Company Number cannot be smaller than %(min_char)s'
                  'characters.'),
                params={'min_char': min_chars}
            )
        return number

    def clean_name(self):
        """Form validation for company names..."""
        name = self.cleaned_data.get('name', None)
        if len(name) < 2:
            raise forms.ValidationError(
                _('Company Name must be longer than 1'
                  'character')
                )
        return name

    class Meta:
        """Class Meta."""

        model = Company
        fields = [
            'name',
            'number',
            'is_renter',
            'is_provider',
            'is_buyer',
            'is_active'
        ]

accounts/views.py
"""Views used on the accounts app."""
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
from django.utils import translation, timezone

from core.views import get_next_url

from .models import Profile, Company, Address
from .forms import CompanyForm, AddressForm

from rest_framework.authtoken.models import Token
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.permissions import IsAuthenticated
from rest_framework.generics import ListCreateAPIView
from rest_framework.viewsets import ReadOnlyModelViewSet
from rest_framework.response import Response

from .serializers import CompanySerializer, AddressSerializer


class ObtainExpiringAuthToken(ObtainAuthToken):
    """Gets an expiring token for rest_framework."""

    def post(self, request, *args, **kwargs):
        """On post, obtain an expiring token."""
        serializer = self.serializer_class(
            data=request.data,
            context={'request': request}
        )
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        token, created = Token.objects.get_or_create(user=user)
        if not created:
            token.created = timezone.now()
            token.save()
        return Response({'token': token.key})


class CompanyViewSet(ReadOnlyModelViewSet):
    """Viewset to provide an API for the Companies."""

    permission_classes = (IsAuthenticated,)
    queryset = Company.objects.all()
    serializer_class = CompanySerializer
    lookup_field = 'number'


class AddressListAPIView(ListCreateAPIView):
    """List Addresses api."""

    serializer_class = AddressSerializer

    def get_queryset(self, *args, **kwargs):
        """Queryset the addresses for either a company or a profile."""
        company = Company.objects.get(number=self.kwargs.get('number'))
        return company.addresses.all()

    def get(self, request, *args, **kwargs):
        """Get a list of addresses."""
        return self.list(request, *args, **kwargs)


class _LoginView(LoginView):
    """Login View overload."""

    def get_success_url(self):
        """Set the correct language based on user preferences."""
        url = super().get_success_url()
        user = self.request.user
        # maybe check if login was successful?
        translation.activate(user.language)
        self.request.session[translation.LANGUAGE_SESSION_KEY] = user.language
        return url


class _LogoutView(LogoutView):
    """Logout view overload."""

    def get_next_page(self):
        """Restore language to application default.

        This may be deprecated, investigate if this is still necesary.
        """
        next_page = super().get_next_page()
        translation.deactivate()
        self.request.session[translation.LANGUAGE_SESSION_KEY] = \
            translation.get_language()
        # settings.LANGUAGE_CODE?
        return next_page


class CompanyListView(PermissionRequiredMixin, ListView):
    """Logic to show a list of a company."""

    model = Company
    context_object_name = 'company_list'
    permission_required = ('accounts.can_see_company_link')
    title = None

    def get_context_data(self, *args, **kwargs):
        """Set context expected for the template."""
        translation.activate(self.request.user.language)
        context = super().get_context_data(*args, **kwargs)
        context['company_link_class'] = 'active'
        if self.title:
            context['title'] = self.title
        return context


class CompanyCreateView(PermissionRequiredMixin, CreateView):
    """Logic to create a company."""

    permission_required = (
        'accounts.can_see_company_link',
        'accounts.add_company',
    )
    form_class = CompanyForm
    template_name = 'accounts/company_form.html'
    context_object_name = 'company'
    title = None

    def get_success_url(self):
        """Get correct redirect after creation of a Company."""
        next_url, kwargs = get_next_url(self.request.GET.get('next', None))
        if not next_url:
            next_url = 'accounts:companies'
        return reverse_lazy(next_url, kwargs=kwargs)

    def get_form_kwargs(self):
        """Get extra form arguments required by Company Form."""
        kwargs = super().get_form_kwargs()
        kwargs['modified_by'] = self.request.user
        return kwargs

    def get_context_data(self, *args, **kwargs):
        """Set context expected by the template."""
        context = super().get_context_data(*args, **kwargs)
        context['company_link_class'] = 'active'
        if self.title:
            context['title'] = self.title
        return context


class CompanyUpdateView(PermissionRequiredMixin, UpdateView):
    """Logic required for updating of a company."""

    permission_required = ('accounts.change_company')
    model = Company
    form_class = CompanyForm
    template_name = 'accounts/company_form.html'
    context_object_name = "company"
    title = None
    slug_field = 'number'
    slug_url_kwarg = 'number'

    def get_success_url(self):
        """Get correct redirection."""
        next_url, kwargs = get_next_url(self.request.GET.get('next', None))
        if not next_url:
            next_url = 'accounts:companies'
        return reverse_lazy(next_url, kwargs=kwargs)

    def get_form_kwargs(self):
        """Get extra arguments required by the form."""
        kwargs = super().get_form_kwargs()
        kwargs['modified_by'] = self.request.user
        return kwargs

    def get_context_data(self, *args, **kwargs):
        """Get context data required by template."""
        context = super().get_context_data(*args, **kwargs)
        context['company_link_class'] = 'active'
        context['addresses'] = self.object.addresses.all()
        if self.title:
            context['title'] = self.title
        return context


class AddressListView(PermissionRequiredMixin, ListView):
    """Display a list of addresses for Companies or Profiles.

    TODO: implement the functionality for Profiles
    """

    model = Address
    context_object_name = 'address_list'
    permission_required = ('accounts.can_see_company_link')
    title = None

    def get_queryset(self):
        """Get the addresses either from a company or a profile."""
        number = self.kwargs.get('number')
        username = self.kwargs.get('username')
        if number:
            company = Company.objects.get(number=number)
        if username:
            profile = Profile.objects.get(username=username)

        return company.addresses.all() if company else profile.addresses.all()

    def get_context_data(self, *args, **kwargs):
        """Get extra context data required by template."""
        context = super().get_context_data(*args, **kwargs)
        context['number'] = self.kwargs.get('number')
        if self.title:
            context['title'] = self.title
        return context


class AddressCreateView(PermissionRequiredMixin, CreateView):
    """Logic for creating an Address."""

    permission_required = ('accounts.add_address')
    form_class = AddressForm
    template_name = 'accounts/address_form.html'
    title = None
    company = None
    profile = None

    def get_success_url(self):
        """Get redirect url after successful creation of Address."""
        next_url, kwargs = get_next_url(self.request.GET.get('next', None))
        if not next_url:
            next_url = 'accounts:company_addresses'
            kwargs['number'] = self.kwargs.get('number')
        return reverse_lazy(next_url, kwargs=kwargs)

    def get_form_kwargs(self):
        """Get extra arguments required by the form."""
        kwargs = super().get_form_kwargs()
        kwargs['modified_by'] = self.request.user
        kwargs['number'] = self.kwargs.get('number')
        return kwargs


class AddressUpdateView(PermissionRequiredMixin, UpdateView):
    """Logic required to update an Address."""

    model = Address
    form_class = AddressForm
    template_name = 'accounts/address_form.html'
    title = None
    permission_required = ('accounts.add_address')

    def get_success_url(self):
        """Get correct redirection url after update of Address.

        TODO: use for profiles as well
        """
        next_url, kwargs = get_next_url(self.request.GET.get('next', None))
        if not next_url:
            next_url = 'accounts:company_addresses'
            kwargs['number'] = self.kwargs.get('number')
        return reverse_lazy(next_url, kwargs=kwargs)

    def get_form_kwargs(self):
        """Get extra arguments required by the form."""
        kwargs = super().get_form_kwargs()
        kwargs['modified_by'] = self.request.user
        kwargs['number'] = self.kwargs.get('number')
        return kwargs

accounts/templates/accounts/address_form.html
{% extends "core/base.html" %}
{% load widget_tweaks %}
{% load i18n %}

{% block main %}
<div class="row">
  <form class="col-md-4 offset-md-4" method='post'>{% csrf_token %}

    {% if form.errors %}
    <div class="alert alert-danger">
      {% trans "Your submition has errors" %}
      <ul>
        {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
    <div class="form-group">
      <label for="{{ form.type.id_for_label }}" class="form-control-label">
        {% trans "Address Type" %}:
      </label>
      {% if form.type.errors %}
        {{ form.type | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.type.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.type | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    <div class="form-group">
      <label for="{{ form.address1.id_for_label }}" class="form-control-label">
        {% trans "Address 1" %}:
      </label>
      {% if form.address1.errors %}
        {{ form.address1 | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.address1.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.address1 | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    <div class="form-group">
      <label for="{{form.address2.id_for_label }}" class="form-control-label">
        {% trans "Address 2" %}:
      </label>
      {% if form.address2.errors %}
        {{ form.address2 | add_class:"form-control" | add_class:"is-invalid" }}
        <div class="invalid-feedback">
        {% for error in form.address2.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.address2 | add_class:"form-control" }}
      {% endif %}
    </div>
    <div class="form-group">
      <label for="{{form.region.id_for_label }}" class="form-control-label">
        {% trans "Region" %}:
      </label>
      {% if form.region.errors %}
        {{ form.region | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.region.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.region | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    <div class="form-group">
      <label for="{{form.city.id_for_label }}" class="form-control-label">
        {% trans "City" %}:
      </label>
      {% if form.city.errors %}
        {{ form.city | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.city.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.city | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    <div class="form-group">
      <label for="{{form.phone.id_for_label }}" class="form-control-label">
        {% trans "Phone" %}:
      </label>
      {% if form.phone.errors %}
        {{ form.phone | add_class:"form-control" | add_class:"is-invalid" }}
        <div class="invalid-feedback">
        {% for error in form.phone.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.phone | add_class:"form-control" }}
      {% endif %}
    </div>
    <div class="form-group">
      <label for="{{form.extension.id_for_label }}" class="form-control-label">
        {% trans "Extension" %}:
      </label>
      {% if form.extension.errors %}
        {{ form.extension | add_class:"form-control" | add_class:"is-invalid" }}
        <div class="invalid-feedback">
        {% for error in form.extension.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.extension | add_class:"form-control" }}
      {% endif %}
    </div>
    <div class="form-group">
      <label for="{{form.fax.id_for_label }}" class="form-control-label">
        {% trans "Fax" %}:
      </label>
      {% if form.fax.errors %}
        {{ form.fax | add_class:"form-control" | add_class:"is-invalid" }}
        <div class="invalid-feedback">
        {% for error in form.fax.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.fax | add_class:"form-control" }}
      {% endif %}
    </div>
    <div class="form-group">
      <label for="{{form.email.id_for_label }}" class="form-control-label">
        {% trans "Email" %}:
      </label>
      {% if form.email.errors %}
        {{ form.email | add_class:"form-control" | add_class:"is-invalid" }}
        <div class="invalid-feedback">
        {% for error in form.email.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.email | add_class:"form-control" }}
      {% endif %}
    </div>

    <div class="form-check">
    {{form.is_active | add_class:"form-check-input" }}
      <label for="{{ form.is_active.id_for_label }}" class="form-check-label">
        {% trans "Active" %}
      </label>
    </div>

    <div class="form-group">
      {% if form.company %}
        <a href="{% url "accounts:company_addresses" form.company.number %}" class="btn btn-outline-primary col-md-12">{% trans "Addresses" %}</a>
      {% else %}
        <p>{% trans "Support for profile addresses comming soon." %}</p>
      {% endif %}
      <input class="btn btn-primary col-md-12" type="submit" value="{% trans 'Save'%}" />
    </div>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/address_list.html
{% extends "core/base.html" %}
{% load i18n %}

{% block main %}
{% if title %}
<div class="jumbotron">
  {{ title }}
</div>
{% endif %}
<div class="row">
  <div class="col-md-10 offset-md-1">
    {% if address_list %}
    <table class="table table-sm table-hover table-responsive">
      <thead>
        <tr>
          <th>{% trans "Actions" %}</th>
          <th>{% trans "Address" %}</th>
          <th>{% trans "Phone" %}</th>
          <th>{% trans "Email" %}</th>
          <th>{% trans "Active" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for address in address_list %}
        <tr>
          <td><a href={% url "accounts:company_address_update" address.content_object.number address.id %}>{% trans "Edit" %}</a></td>
          <td>{{ address }}</td>
          <td>{{ address.phone }}</td>
          <td>{{ address.email }}</td>
          <td>{{ address.is_active|yesno:_("Yes,No")  }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <h5>{% trans "No Addresses available." %}</h5>
    {% endif %}
  </div>
</div>
{% if perms.accounts.add_address %}
<div class="row">
  <div class="col-md-12">
    <a class='btn btn-outline-primary col-md-2 offset-md-10'
      href="{% url 'accounts:company_address_add' number %}">
      {% trans "Add Address" %}
    </a>
  </div>
</div>
{% endif %}
{% endblock %}

accounts/templates/accounts/company_form.html
{% extends "core/base.html" %}
{% load widget_tweaks %}
{% load i18n %}

{% block main %}
<div class="row">
  <form class="col-md-4 offset-md-4" method='post'>{% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger">
      {% trans "Your submition has errors" %}
      <ul>
        {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

    <div class="form-group">
      <label for="{{form.name.id_for_label }}" class="form-control-label">
        {% trans "Name" %}:
      </label>
      {% if form.name.errors %}
        {{ form.name | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.name.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.name | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>

    <div class="form-group">
      <label for="{{ form.number.id_for_label }}" class="form-control-label">
        {% trans "Number" context "company number" %}:
      </label>
      {% if form.number.errors %}
        {{ form.number | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
          {% for error in form.number.errors %}
            <p>{{ error }}</p>
          {% endfor %}
        </div>
      {% else %}
        {{ form.number | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>

    <div class="form-check form-check-inline">
      {{ form.is_provider | add_class:"form-check-input" }}
      <label for="{{form.is_provider.id_for_label }}" class="form-check-label">
        {% trans "Provider" %}
      </label>
      {{ form.is_renter | add_class:"form-check-input" }}
      <label for="{{form.is_renter.id_for_label }}" class="form-check-label">
        {% trans "Renter" %}
      </label>
      {{ form.is_buyer | add_class:"form-check-input" }}
      <label for="{{form.is_buyer.id_for_label }}" class="form-check-label">
        {% trans "Buyer" %}
      </label>
    </div>
    <div class="form-check">
    {{form.is_active | add_class:"form-check-input" }}
      <label for="{{ form.is_active.id_for_label }}" class="form-check-label">
        {% trans "Active" %}
      </label>
    </div>
    <div class="form-group">
      <a href="{% url "accounts:companies"%}" class="btn btn-outline-primary col-md-12">{% trans "Companies" %}</a>
      {% if form.number.value %}
        <a href="{% url "accounts:company_addresses" form.number.value %}" class="btn btn-outline-primary col-md-12">{% trans "Addresses" %}</a>
      {% endif %}
        <input class="btn btn-primary col-md-12" type="submit" value="{% trans 'Save'%}" />
    </div>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/company_list.html
{% extends "core/base.html" %}
{% load widget_tweaks %}
{% load i18n %}

{% block main %}
{% if title %}
<div class="jumbotron">
  {{ title }}
</div>
{% endif %}
<div class="row">
  <div class="col-md-9 offset-md-2">
    {% if company_list %}
    <table class="table table-sm table-hover table-responsive">
      <thead>
        <tr>
          <th>{% trans "Actions" %}</th>
          <th>{% trans "Number" context "company number" %}</th>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Provider" %}</th>
          <th>{% trans "Renter" %}</th>
          <th>{% trans "Buyer" %}</th>
          <th>{% trans "Active" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for company in company_list %}
        <tr>
          <td>
            {% if perms.accounts.change_company %}
            <a href={% url "accounts:company_update" company.number %}>
              {% trans "Edit" %}
            </a>
            {% endif %}
          </td>
          <td>{{ company.number }}</td>
          <td>{{ company.name }}</td>
          <td><input type="checkbox" disabled {% if company.is_provider %}checked{% endif %} /></td>
          <td><input type="checkbox" disabled {% if company.is_renter %}checked{% endif %} /></td>
          <td><input type="checkbox" disabled {% if company.is_buyer %}checked{% endif %} /></td>
          <td>{{ company.is_active|yesno:_("Yes,No") }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <h5>{% trans "No Companies available." %}</h5>
    {% endif %}
  </div>
</div>
{% if perms.accounts.add_company %}
<div class="row">
  <div class="col-md-12">
    <a class='btn btn-outline-primary col-md-2 offset-md-10'
      href="{% url "accounts:company_add" %}">
      {% trans "Add Company" %}
    </a>
  </div>
</div>
{% endif %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends "core/base.html" %}
{% load widget_tweaks %}
{% load i18n %}

{% block main %}

<div class="row">
  <form class="col-md-4 offset-md-4" method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    {% if next %}
    <div class="alert alert-warning">
      {% if user.is_authenticated %}
        {% trans "Your account doesn't have access to this page. To proceed, please login with an account that has access." %}
      {% else %}
        {%trans "Please login to see this page." %}
      {% endif %}
    </div>
    {% endif %}
    {% if form.errors %}
    <div class="alert alert-danger">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
    {% endif %}


    <div class="form-group {% if form.email.errors %} is-invalid {% endif %}">
      {% if form.username.errors %}
      <ul>
        {% for error in form.username.errors %}
        <li class="invalid-feedback">{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
      <label for="{{form.email.id_for_label }}" class="form-control-label">
        {% trans "Username" %}:
      </label>
      {{ form.username | add_class:"form-control" | attr:"required" }}
    </div>

    <div class="form-group {% if form.password.errors %} is-invalid {% endif %}">
      {% if form.password.errors %}
      <ul>
        {% for error in form.password.errors %}
        <li class="invalid-feedback">{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
      <label for="{{form.password.id_for_label}}">
        {% trans "Password" %}:
      </label>
      {{ form.password | add_class:"form-control" | attr:"required" }}
    </div>
    <div class="form-group">
      <input class="btn btn-primary col-md-12" type="submit" value="{% trans 'Login'%}" />
      <input type="hidden" name="next" value="{{ next }}" />
    </div>
  </form>
</div>

{% endblock %}