core/urls.py
from django.urls import path

from .views import Homepage

app_name = 'core'

urlpatterns = [
    path('', Homepage.as_view(), name="home"),
]

purchases/urls.py
"""Urls for the purchases app."""
from django.urls import path

from .views import (
    BillCreateView,
    BillListView,
    BillUpdateView,
    ProductListView,
    ProductCreateView,
    ProductUpdateView
)

app_name = 'purchases'

urlpatterns = [
    path('bill/add/', BillCreateView.as_view(), name='bill_add'),
    path('bills/', BillListView.as_view(), name='bills'),
    path(
        'bills/<slug:number>',
        BillUpdateView.as_view(),
        name='bill_update'
    ),
    path(
        'bills/<slug:receipt_number>/products',
        ProductListView.as_view(),
        name='products'
    ),
    path(
        'receipts/<slug:receipt_number>/product/add',
        ProductCreateView.as_view(),
        name='product_add'
    ),
    path(
        'receipts/<slug:number>/product/<slug:serial_number>',
        ProductUpdateView.as_view(),
        name='product_update'
    ),
]

purchases/models.py
"""Models used in purchases module."""
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.models import Auditable, AbstractProduct

from . import STATUSES, LOADING, DELETED


class Bill(Auditable):
    """A bill on the system."""

    number = models.CharField(max_length=20, unique=True)
    purchase_date = models.DateField()
    company = models.ForeignKey(
        settings.COMPANY_MODEL,
        on_delete=models.DO_NOTHING,
        related_name="purchase_bills"
    )
    currency = models.ForeignKey(
        settings.CURRENCY_MODEL,
        on_delete=models.DO_NOTHING,
        related_name='+'
    )
    status = models.CharField(
        max_length=10,
        choices=sorted(STATUSES.items()),
        default=LOADING
    )
    price = models.DecimalField(max_digits=12, decimal_places=2)

    @property
    def products_price(self, *args, **kwargs):
        """Get the prices of all the products in all receipts.

        WARNING:
            * O(n^2) => going into receipts and then into products
        """
        return sum([r.products_price for r in self.receipt_set.all()])

    def delete(self, *args, **kwargs):
        """Set the status of the bill to deleted."""
        if kwargs.get('force', None):
            super().delete(*args, **kwargs)
        else:
            self.status = DELETED
            self.save(*args, **kwargs)

    def __str__(self):
        """See number when printing."""
        return str(self.number)

    class Meta:
        """Metadata."""

        verbose_name = _('Bill')
        verbose_name_plural = _('Bills')


class Receipt(models.Model):
    """A receipt on the system."""

    number = models.CharField(max_length=20)
    bill = models.ForeignKey(Bill, on_delete=models.CASCADE)

    @property
    def products_price(self, *args, **kwargs):
        """Total price of the products in the receipt."""
        return sum([p.price for p in self.product_set.all()])

    def __str__(self):
        """Show number of a receipt."""
        return self.number

    class Meta:
        """Metaclass."""

        verbose_name = _('Purchase Receipt')
        verbose_name_plural = _('Purchase Receipt')


class ProductManager(models.Manager):
    """Product Manager."""

    def create(self, *args, **kwargs):
        """On creation of a product.

        Need this for the creation of a warehouse product.
        a wharehouse product is an auditable model.
        """
        self.model.created_by = kwargs.pop('created_by', None)
        return super(ProductManager, self).create(*args, **kwargs)


class Product(AbstractProduct):
    """Product information valid for purchases."""

    receipt = models.ForeignKey(Receipt, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=12, decimal_places=2)

    objects = ProductManager()

    def __init__(self, *args, **kwargs):
        """Save the price of this product (for eddits only)."""
        super().__init__(*args, **kwargs)
        self.old_price = self.price

    def __str__(self):
        """Show serial number on display."""
        return self.serial_number

    class Meta:
        """Metaclass."""

        verbose_name = _('Purchased Product')
        verbose_name_plural = _('Purchased Products')

purchases/views.py
"""Views for the purchases module."""
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin
    )
from django.shortcuts import get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy

from core.views import get_next_url

from .models import Bill, Product, Receipt
from .forms import BillForm, ProductForm, CreateProductsForm


class BillUpdateView(PermissionRequiredMixin, UpdateView):
    """Updating a Bill."""

    permission_required = (
        'purchases.change_bill'
    )
    form_class = BillForm
    template_name = 'purchases/bill_form.html'
    context_object_name = 'bill'
    model = Bill
    title = None
    slug_field = 'number'
    slug_url_kwarg = 'number'

    def get_success_url(self):
        """Get correct url on successful creation of a bill."""
        next_url, kwargs = get_next_url(self.request.GET.get('next', None))
        if not next_url:
            next_url = 'purchases:bills'
        return reverse_lazy(next_url, kwargs=kwargs)

    def get_form_kwargs(self):
        """Get extra information for the form."""
        kwargs = super().get_form_kwargs()
        kwargs['modified_by'] = self.request.user
        bill = get_object_or_404(Bill, number=self.kwargs.get('number'))
        kwargs['bill'] = bill
        return kwargs

    def get_context_data(self, *args, **kwargs):
        """Extra data for the bill form."""
        context = super().get_context_data(*args, **kwargs)
        if self.title:
            context['title'] = self.title
        return context


class BillCreateView(PermissionRequiredMixin, CreateView):
    """Create a bill."""

    permission_required = (
        'purchases.add_bill',
    )
    form_class = BillForm
    template_name = 'purchases/bill_form.html'
    context_object_name = 'bill'
    title = None

    def get_success_url(self):
        """On sucessful creation redirect to correct url."""
        next_url, kwargs = get_next_url(self.request.GET.get('next', None))
        if not next_url:
            next_url = 'purchases:bills'
        return reverse_lazy(next_url, kwargs=kwargs)

    def get_form_kwargs(self):
        """Extra arguments for the form."""
        kwargs = super().get_form_kwargs()
        kwargs['modified_by'] = self.request.user
        return kwargs

    def get_context_data(self, *args, **kwargs):
        """Extra data for the templates."""
        context = super().get_context_data(*args, **kwargs)
        if self.title:
            context['title'] = self.title
        return context


class BillListView(LoginRequiredMixin, ListView):
    """TODO: add permissions."""

    model = Bill
    context_object_name = 'bill_list'
    title = None

    def get_context_data(self, *args, **kwargs):
        """Get extra contex data."""
        context = super().get_context_data(*args, **kwargs)
        context['purchases_ddl'] = 'active'
        context['purchases_bills'] = 'active'
        if self.title:
            context['title'] = self.title
        return context


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    """Update a single product."""

    permission_required = (
        'purchases.change_product'
    )
    form_class = ProductForm
    template_name = 'purchases/product_update_form.html'
    context_object_name = 'product'
    title = None
    model = Product
    slug_field = 'serial_number'
    slug_url_kwarg = 'serial_number'

    def get_success_url(self):
        """Get success url for products."""
        next_url, kwargs = get_next_url(self.request.GET.get('next', None))
        if not next_url:
            next_url = 'purchases:products'
            kwargs = {'receipt_number': self.kwargs.get('number', None)}
        return reverse_lazy(next_url, kwargs=kwargs)

    def get_form_kwargs(self):
        """Get user id for the init of the form."""
        kwargs = super().get_form_kwargs()
        kwargs['modified_by'] = self.request.user
        return kwargs

    def get_context_data(self, *args, **kwargs):
        """Get extra context data."""
        context = super().get_context_data(*args, **kwargs)
        context['receipt_number'] = self.kwargs.get('number', None)
        if self.title:
            context['title'] = self.title
        return context


class ProductCreateView(PermissionRequiredMixin, CreateView):
    """Create a product."""

    permission_required = (
        'purchases.add_product',
    )
    form_class = CreateProductsForm
    template_name = 'purchases/products_create_form.html'
    context_object_name = 'product'
    title = None

    def get_success_url(self):
        """On success creation of products send them to the bills view."""
        next_url, kwargs = get_next_url(self.request.GET.get('next', None))
        if not next_url:
            next_url = 'purchases:bills'
        return reverse_lazy(next_url, kwargs=kwargs)

    def get_form_kwargs(self):
        """Extra arguments required by the form."""
        kwargs = super().get_form_kwargs()
        kwargs['receipt_number'] = self.kwargs.get('receipt_number')
        kwargs['modified_by'] = self.request.user
        kwargs['serial_number'] = self.kwargs.get('serial_number')
        return kwargs

    def get_context_data(self, *args, **kwargs):
        """Get extra context data for the template."""
        context = super().get_context_data(*args, **kwargs)
        if self.title:
            context['title'] = self.title
        return context


class ProductListView(PermissionRequiredMixin, ListView):
    """Product List View."""

    permission_required = (
        'purchases.add_product',
        'purchases.change_product'
    )
    model = Product
    context_object_name = 'product_list'
    title = None

    def get_queryset(self):
        """Get the products for the receipt."""
        receipt = Receipt.objects.get(number=self.kwargs.get('receipt_number'))
        return Product.objects.filter(receipt=receipt)

    def get_context_data(self, *args, **kwargs):
        """Get context data for the template."""
        context = super().get_context_data(*args, **kwargs)
        context['purchases_ddl'] = 'active'
        context['purchases_products'] = 'active'
        context['receipt_number'] = self.kwargs.get('receipt_number')
        if self.title:
            context['title'] = self.title
        return context

purchases/templates/purchases/bill_form.html
{% extends "core/base.html" %}
{% load widget_tweaks %}
{% load i18n %}

{% block main %}
<div class="row">
  <form class="col-md-4 offset-md-4" method='post'>{% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger">
      {% trans "Your submition has errors" %}
      <ul>
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
      </ul>
    </div>
    {% endif %}

    <div class="form-group">
      <label for="{{form.number.id_for_label }}" class="form-control-label">
        {% trans "Number" %}:
      </label>
      {% if form.number.errors %}
        {{ form.number | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.number.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.number | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    <div class="form-group">
      {# TODO: make this a date picker #}
      <label for="{{form.purchase_date.id_for_label }}" class="form-control-label">
        {% trans "Purchase Date" %}:
      </label>
      {% if form.purchase_date.errors %}
        {{ form.purchase_date | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.purchase_date.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.purchase_date | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    <div class="form-group">
      <label for="{{form.company.id_for_label }}" class="form-control-label">
        {% trans "Company" %}:
      </label>
      {% if form.company.errors %}
        {{ form.company | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.company.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.company | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    <div class="form-group">
      <label for="{{form.currency.id_for_label }}" class="form-control-label">
        {% trans "Currency" %}:
      </label>
      {% if form.currency.errors %}
        {{ form.currency | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.currency.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.currency | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    <div class="form-group">
      <label for="{{form.price.id_for_label }}" class="form-control-label">
        {% trans "Price" %}:
      </label>
      {% if form.price.errors %}
        {{ form.price | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.price.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.price | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    <div class="form-group">
      <label for="{{form.price.id_for_label }}" class="form-control-label">
        {% trans "Receipts" %}:
      </label>
      {% if form.receipts.errors %}
        {{ form.receipts | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.receipts.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.receipts | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    <div class="form-group">
        <input class="btn btn-primary col-md-12" type="submit" value="{% trans 'Save'%}" />
    </div>

  </form>
</div>

{% endblock %}

purchases/templates/purchases/bill_list.html
{% extends "core/base.html" %}
{% load widget_tweaks %}
{% load i18n %}
{% load bill_status %}
{% load currency %}

{% block main %}
{% if title %}
<div class="jumbotron">
  {{ title }}
</div>
{% endif %}
<div class="row">
  <div class="col-md-9 offset-md-2">
    {% if bill_list %}
    <table class="table table-sm table-hover table-responsive">
      <thead>
        <tr>
          <th>{% trans "Actions" %}</th>
          <th>{% trans "Number" %}</th>
          <th>{% trans "Purchase Date" %}</th>
          <th>{% trans "Company" %}</th>
          <th>{% trans "Status" %}</th>
          <th>{% trans "Currency" %}</th>
          <th>{% trans "Price" %}</th>
          <th>{% trans "Receipts" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for bill in bill_list %}
        <tr>
          <td>
            {% if perms.purchases.change_bill %}
            <a href={% url "purchases:bill_update" bill.number %}>
              {% trans "Edit" %}
            </a>
            {% endif %}
          </td>
          <td>{{ bill.number }}</td>
          <td>{{ bill.purchase_date }}</td>
          <td>{{ bill.company }}</td>
          <td>{{ bill.status|get_bill_status_display }}</td>
          <td>{{ bill.currency }}</td>
          <td>{{ bill.price }}</td>
          <td>
            {% for r in bill.receipt_set.all %}
             <a href="{% url 'purchases:products' r.number %}">{{ r }}</a>
            {% endfor %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <h5>{% trans "No Bills available." %}</h5>
    {% endif %}
  </div>
</div>
{% if perms.purchases.add_bill %}
<div class="row">
  <div class="col-md-12">
    <a class='btn btn-outline-primary col-md-2 offset-md-10'
      href="{% url "purchases:bill_add" %}">
      {% trans "Create Bill" %}
    </a>
  </div>
</div>
{% endif %}
{% endblock %}

purchases/templates/purchases/product_list.html
{% extends "core/base.html" %}
{% load widget_tweaks %}
{% load i18n %}

{% block main %}
{% if title %}
<div class="jumbotron">
  {{ title }}
</div>
{% endif %}
<div class="row">
  <div class="col-md-9 offset-md-2">
    {% if product_list %}
    <table class="table table-sm table-hover table-responsive">
      <thead>
        <tr>
          <th>{% trans "Actions" %}</th>
          <th>{% trans "Serial Number" %}</th>
          <th>{% trans "Receipt" %}</th>
          <th>{% trans "Bill" %}</th>
          <th>{% trans "Price" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for product in product_list %}
        <tr>
          <td>
            {% if perms.purchases.change_product %}
            <a href="{% url 'purchases:product_update' product.receipt.number product.serial_number %}">
              {% trans "Edit" %}
            </a>
            {% endif %}
          </td>
          <td>{{ product.serial_number }}</td>
          <td>{{ product.receipt }}</td>
          <td>{{ product.receipt.bill }}</td>
          <td>{{ product.price }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <h5>{% trans "No Products available." %}</h5>
    {% endif %}
  </div>
</div>
{% if perms.purchases.add_product %}
<div class="row">
  <div class="col-md-12">
    <a class='btn btn-outline-primary col-md-2 offset-md-10'
      href="{% url 'purchases:product_add' receipt_number %}">
      {% trans "Add Product" %}
    </a>
  </div>
</div>
{% endif %}
{% endblock %}

purchases/templates/purchases/product_update_form.html
{% extends "core/base.html" %}
{% load widget_tweaks %}
{% load i18n %}

{% block main %}
<div class="row">
  <form class="col-md-4 offset-md-4" method='post'>{% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger">
      {% trans "Your submition has errors" %}
      <ul>
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
      </ul>
    </div>
    {% endif %}

    <div class="form-group">
      <label for="{{ form.serial_number.id_for_label }}" class="form-control-label">
        {% trans "Serial Number" %}:
      </label>
      {% if form.serial_number.errors %}
        {{ form.serial_number | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.serial_number.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.serial_number | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    <div class="form-group">
      <label for="{{form.price.id_for_label }}" class="form-control-label">
        {% trans "Price" %}:
      </label>
      {% if form.price.errors %}
        {{ form.price | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.price.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.price | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    <div class="form-group">
      <label for="{{form.receipt.id_for_label }}" class="form-control-label">
        {% trans "Receipt" %}:
      </label>
      {% if form.receipt.errors %}
        {{ form.receipt | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.receipt.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.receipt | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    <div class="form-group">
      <a href="{% url "purchases:products" receipt_number %}" class="btn btn-outline-primary col-md-12">{% trans "Products" %}</a>
      <input class="btn btn-primary col-md-12" type="submit" value="{% trans 'Save'%}" />
    </div>

  </form>
</div>

{% endblock %}

purchases/templates/purchases/products_create_form.html
{% extends "core/base.html" %}
{% load widget_tweaks %}
{% load i18n %}

{% block main %}
<div class="row">
  <form class="col-md-4 offset-md-4" method='post'>{% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger">
      {% trans "Your submition has errors" %}
      <ul>
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
      </ul>
    </div>
    {% endif %}

    <div class="form-group">
      <label for="{{ form.numbers.id_for_label }}" class="form-control-label">
        {% trans "Serial Numbers" %}:
      </label>
      {% if form.numbers.errors %}
        {{ form.numbers | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.numbers.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.numbers | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    {# get currency from the bill... #}
    <div class="form-group">
      <label for="{{form.price.id_for_label }}" class="form-control-label">
        {% trans "Price:" %}
      </label>
      {% if form.price.errors %}
        {{ form.price | add_class:"form-control" | add_class:"is-invalid" | attr:"required"}}
        <div class="invalid-feedback">
        {% for error in form.price.errors %}
          <p class="form-control-feedback">{{ error }}</p>
        {% endfor %}
        </div>
      {% else %}
        {{ form.price | add_class:"form-control" | attr:"required" }}
      {% endif %}
    </div>
    <div class="form-group">
        <input class="btn btn-primary col-md-12" type="submit" value="{% trans 'Save'%}" />
    </div>

  </form>
</div>

{% endblock %}