accounts/urls.py
"""Urls used in the accounts app."""
from django.urls import include, path

from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.routers import DefaultRouter

from .views import (
    _LoginView,
    _LogoutView,
    CompanyListView,
    CompanyCreateView,
    CompanyUpdateView,
    AddressListView,
    AddressCreateView,
    AddressUpdateView,
    CompanyViewSet,
    AddressListAPIView,
    ObtainExpiringAuthToken,
)

app_name = 'accounts'

urlpatterns = [
    path(
        'login/',
        _LoginView.as_view(
            template_name='accounts/login.html',
            extra_context={'login_active': 'active'}
            ),
        name='login'
        ),
    path('logout/', _LogoutView.as_view(next_page='core:home'), name='logout'),
    path('companies/', CompanyListView.as_view(), name='companies'),
    path('companies/add/', CompanyCreateView.as_view(), name='company_add'),
    path(
        'companies/<int:number>/',
        CompanyUpdateView.as_view(),
        name='company_update'
        ),
    path(
        'companies/<int:number>/addresses/',
        AddressListView.as_view(),
        name='company_addresses'
        ),
    path(
        'companies/<int:number>/address/add/',
        AddressCreateView.as_view(),
        name='company_address_add'
        ),
    path(
        'companies/<int:number>/address/<int:pk>/',
        AddressUpdateView.as_view(),
        name='company_address_update'
        ),
]

router = DefaultRouter(trailing_slash=False)
router.register(r'api/companies', CompanyViewSet)

api_viewsets = [
    path('', include(router.urls)),
    ]
api_urlpatterns = format_suffix_patterns([
    path(
        'api/companies/<slug:number>/addresses',
        AddressListAPIView.as_view(),
        name='api-company_addresses'
        ),
    path('api/token', ObtainExpiringAuthToken.as_view(), name='api-get_token'),
])

urlpatterns.extend(api_viewsets)
urlpatterns.extend(api_urlpatterns)

core/urls.py
from django.urls import path

from .views import Homepage

app_name = 'core'

urlpatterns = [
    path('', Homepage.as_view(), name="home"),
]

purchases/urls.py
"""Urls for the purchases app."""
from django.urls import path

from .views import (
    BillCreateView,
    BillListView,
    BillUpdateView,
    ProductListView,
    ProductCreateView,
    ProductUpdateView
)

app_name = 'purchases'

urlpatterns = [
    path('bill/add/', BillCreateView.as_view(), name='bill_add'),
    path('bills/', BillListView.as_view(), name='bills'),
    path(
        'bills/<slug:number>',
        BillUpdateView.as_view(),
        name='bill_update'
    ),
    path(
        'bills/<slug:receipt_number>/products',
        ProductListView.as_view(),
        name='products'
    ),
    path(
        'receipts/<slug:receipt_number>/product/add',
        ProductCreateView.as_view(),
        name='product_add'
    ),
    path(
        'receipts/<slug:number>/product/<slug:serial_number>',
        ProductUpdateView.as_view(),
        name='product_update'
    ),
]

core/models.py
"""Common functionality for models."""
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.forms.models import model_to_dict
from django.utils.translation import gettext as _

# from simple_history.models import HistoricalRecords

from .exceptions import (
    MissingProfileException,
    MissingCreateProfileError,
    MissingUpdateProfileError
)


class AbstractProduct(models.Model):
    """All products must have this behaviour."""

    serial_number = models.CharField(max_length=50, unique=True)

    class Meta:
        """AbstractProduct meta."""

        abstract = True


class ModelDiffMixin:
    """A model mixin that tracks model fields' values.

    It also provides a useful api to know what fields have been changed.
    """

    def __init__(self, *args, **kwargs):
        """Set __initial dictionary."""
        super().__init__(*args, **kwargs)
        self.__initial = self._dict

    @property
    def diff(self):
        """Check differences so far."""
        d1 = self.__initial
        d2 = self._dict
        diffs = [(k, (v, d2[k])) for k, v in d1.items() if v != d2[k]]
        return dict(diffs)

    @property
    def has_changed(self):
        """Check if something has changed."""
        return bool(self.diff)

    @property
    def changed_fields(self):
        """Check which properties have changed."""
        return self.diff.keys()

    def get_field_diff(self, field_name):
        """Return a diff for field if it's changed and None otherwise."""
        return self.diff.get(field_name, None)

    def save(self, *args, **kwargs):
        """Save model and set initial state."""
        super(ModelDiffMixin, self).save(*args, **kwargs)
        self.__initial = self._dict

    @property
    def _dict(self):
        return model_to_dict(
            self,
            fields=[field.name for field in self._meta.fields]
        )


class AuditableQuerySet(models.QuerySet):
    """Options for queries on an auditable."""

    def update(self, *args, **kwargs):
        """Check for modified_by in the query."""
        modified_by = kwargs.get('modified_by', None)
        if not modified_by:
            raise MissingUpdateProfileError()
        return super(AuditableQuerySet, self).update(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """Do not delete?."""
        super().delete(*args, **kwargs)


class AuditableManager(models.Manager):
    """Manager for all auditable models."""

    def get_queryset(self):
        """Get the queryset for auditables."""
        return AuditableQuerySet(self.model, using=self._db)

    def create(self, *args, **kwargs):
        """Create an auditable model.

        Returns:
            A newly created model.

        """
        kwargs = self.clean(*args, **kwargs)
        return super(AuditableManager, self).create(*args, **kwargs)

    def clean(self, *args, **kwargs):
        """Make sure that the kwargs given are proper for saving an auditable.

        created_by, modified_by and force_create can be passed in the kwargs.
        if force_create flag is passed, the method will try to create an
        auditable model with a superuser on the system.

        Raises:
            MissingProfileException:
                * If modified_by and created_by and force_create are not
                  provided.
                * if modified_by and created_by are not provided and
                  force create is provided, but there is no superusers in
                  they system

        Returns:
            A proper version of kwargs.

        """
        modified_by = kwargs.get('modified_by', None)
        created_by = kwargs.pop('created_by', None)
        force_create = kwargs.pop('force_create', None)
        if not modified_by and not created_by:
            # TODO: Identify if force create is a good idea.
            if force_create:
                user_model = get_user_model()
                created_by = user_model.objects.filter(
                    is_superuser=True
                ).first()
                if not created_by:
                    raise MissingCreateProfileError(
                        message='No Superuser available for create action.'
                    )
            else:
                raise MissingCreateProfileError()
        kwargs['modified_by'] = created_by if created_by else modified_by
        return kwargs


class Auditable(models.Model):
    """Model an entity that can be auditable.

    When updatig an auditable class, make sure you pass a
    """

    modified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.DO_NOTHING,
        related_name='+'  # dont need reference to who changed the record.
    )
    modified = models.DateTimeField(auto_now=True)
    # comment when running tests...
    # or make ModelMixinTestCase compatible with
    # historical records (Auditable)
    # history = HistoricalRecords(inherit=True)

    objects = AuditableManager()

    MissingProfileException = MissingProfileException

    @property
    def _history_user(self):
        return self.modified_by

    def save(self, *args, **kwargs):
        """Save an auditable model.

        TODO:
        * revise if this approach is good since 'kwargs' are not passed
          from the forms hence we never get the modified by and such.
          Also, if you try to use 'ModelDiffMixin' beware that if the
          same user modifies the model, it won't count as modified...
        * update tests
        """
        modified_by = kwargs.pop('modified_by', None)
        created_by = kwargs.pop('created_by', None)
        if self.id:
            # Update
            if not self.modified_by:
                raise MissingUpdateProfileError(
                    _("Model's modified_by has not been updated.")
                )
            if modified_by:
                self.modified_by = modified_by
        else:
            # Create
            # self.modified_by will be set by the auditable manager's create
            # function. In which case, it will not come in the keyword
            # arguments. this also considers the case where save gets called
            # without the use of manager, in which case, keyword arguments
            # must be provided.
            if not self.modified_by_id and not created_by and not modified_by:
                raise MissingCreateProfileError()
            elif not self.modified_by_id:
                self.modified_by = created_by if created_by else modified_by
        return super(Auditable, self).save(*args, **kwargs)

    class Meta:
        """ClassMeta for Auditable."""

        abstract = True


class SalesTax(Auditable):
    """SalesTaxes applied to apps.

    TODO: write a clean method and format percentage accordingly.
    """

    percentage = models.DecimalField(
        max_digits=5,
        decimal_places=4
    )
    valid_from = models.DateField()
    valid_to = models.DateField()

    def __str__(self):
        """Integer representation of a percentage."""
        return '{}%'.format(int(self.percentage*100))

    class Meta:
        """SalesTax meta"."""

        verbose_name = _('Sales Tax')
        verbose_name_plural = _("Sales Taxes")


class CurrencyManager(AuditableManager):
    """Currency manager."""

    def get_or_create(self, *args, **kwargs):
        """Get a Currency or tries to create one."""
        try:
            c = Currency.objects.get(code=kwargs.get('code'))
        except Currency.DoesNotExist:
            c = super(CurrencyManager, self).create(*args, **kwargs)
        return c


class Currency(Auditable):
    """Currency used in the application."""

    SOL = 'pen'
    DOLLAR = 'usd'
    EURO = 'eur'
    CURRENCIES = {
        SOL: _('Nuevo Sol'),
        DOLLAR: _('Dollar'),
        EURO: _('Euro'),
    }
    SYMBOLS = {
        SOL: 'S/.',
        DOLLAR: '$',
        EURO: '€'
    }
    code = models.CharField(
        choices=sorted(CURRENCIES.items()),
        max_length=3,
        unique=True,
    )
    symbol = models.CharField(
        choices=sorted(SYMBOLS.items()),
        max_length=3,
        unique=True,
        null=True,
        default=None
    )
    exchange_rate = models.DecimalField(
        max_digits=9,
        decimal_places=4,
        null=True,
        default=None,
    )
    exchange_currency = models.ForeignKey(
        settings.CURRENCY_MODEL,
        on_delete=models.DO_NOTHING,
        null=True,
        default=None,
        # TODO change the name? this foreign key maps to the currency that the
        # exchange rate relates to. For example:
        #   code: pen;
        #   symbol: S./;
        #   exchange_rate: 3.51;
        #   exchange_currency: <Dollar currency>
        related_name='related_currency'
    )

    objects = CurrencyManager()

    def __str__(self):
        """Get string representation of Currencies."""
        return self.CURRENCIES[self.code]

    def clean(self):
        """If you have an exchange rate, you must have a currency_id."""
        super(Currency, self).clean()
        if self.exchange_rate and not self.exchange_currency_id:
            raise ValidationError(_('Must provide a exchange currency.'))

    class Meta:
        """Meta class for Currency."""

        verbose_name = _('Currency')
        verbose_name_plural = _("Currencies")

core/forms.py
from django import forms


class AbstractModelForm(forms.ModelForm):
    ''' Represent an abstract model form.
    When a model form is abstract, we dont really have a model for it.
    '''

    def __init__(self, *args, **kwargs):
        ''' get the model from one of the kwargs '''
        model = kwargs.pop('model', None)
        self._meta.model = model if not self._meta.model else self._meta.model
        super(AbstractModelForm, self).__init__(*args, **kwargs)


class AuditableFormMixin(forms.ModelForm):
    ''' in charge of getting a profile for the form. '''

    def __init__(self, *args, **kwargs):
        ''' Get a profile that is modifying/creating the form '''
        self.profile = kwargs.pop('modified_by', None)
        super().__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        ''' '''
        self.instance.modified_by = self.profile
        super().save(*args, **kwargs)

core/views.py
from django.views.generic import TemplateView

def get_next_url(next_string, separator = '-'):
    ''' parses the next_string to look for a url and its keyword arguments
     the url must be of the format:
     <url>[<separator><key>=<value>,<key>=<value>...]
    '''
    kwargs = {}
    next_url = next_string.split(separator) if next_string else None
    url = next_url[0] if next_url else None
    raw_kwargs = next_url[-1] if next_url and len(next_url) > 0 else None
    if raw_kwargs:
        _kwargs = {}
        for kwarg in raw_kwargs.split(','):
            if kwarg:
                lst = kwarg.split('=')
                if len(lst) == 2:
                    _kwargs[lst[0]] = lst[1]
        kwargs = _kwargs
    return (url, kwargs)

class Homepage(TemplateView):
    template_name = 'core/index.html'
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super(Homepage, self).get_context_data(**kwargs)
        if self.extra_context:
            context.update(extra_context)
        return context

core/templates/core/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="{% static 'core/bootstrap-4/css/bootstrap.css' %}">
</head>

<body>
  <div class="container">
    <header class="header clearfix">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url "core:home" %}">Tektronic</a>
        <button class="navbar-toggler" type="buton" data-toggle="collapse"
          data-target="#mainNavMenu" aria-controls="mainNavMenu"
          aria-expanded="false" aria-label="Toggle navigations">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="mainNavMenu">
          <ul class="navbar-nav mr-auto">
            {% if perms.accounts.can_see_company_link %}
            <li class="nav-item {{ company_link_class }}">
              <a class="nav-link" href="{% url 'accounts:companies' %}">
                {% trans "Companies" %}
              </a>
            </li>
            {% endif %}
            {% if perms.purchases.can_see_purchases_link%}
            <li class="nav-item dropdown {{ purchases_ddl }}">
              <a class="nav-link dropdown-toogle"
                href="#" id="purchasesDDMenu" role="button"
                data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
                {% trans "Purchases" %}
              </a>
              <div class="dropdown-menu" aria-labelledby="purchasesDDMenu">
                <a class="dropdown-item {{ purchases_bills }}"
                  href="{% url 'purchases:bills' %}">
                  {% trans "Bills" %}
                </a>
              </div>
            </li>
            {% endif %}

            {% if perms.warehouse.can_see_warehouse_link %}
            <li class="nav-item dropdown {{ warehouse_ddl }}">
              <a class="nav-link dropdown-toogle"
                href="#" id="warehouseDDMenu" role="button"
                data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
                {% trans "Warehouse" %}
              </a>
              <div class="dropdown-menu" aria-labelledby="warehouseDDMenu">
                <a class="dropdown-item {{ warehouse_products }}" href="#">
                  {% trans "Products" %}
                </a>
                <a class="dropdown-item {{ warehouse_add}}" href="#">
                  {% trans "Add Products" %}
                </a>
              </div>
            </li>
            {% endif %}
          </ul>
          <div class="navbar-nav ml-auto">
            {% if not user.is_authenticated %}
            <a class="nav-item nav-link {{ login_active }}" href="{% url "accounts:login" %}">
              {% trans "Login" %}
            </a>
            {% else %}
            <a class="nav-item nav-link" href="{% url "accounts:logout" %}">
              {% trans "Logout" %}
            </a>
            {% endif %}
          </div>
        </div>
      </nav>
    </header>

    <main role="main">
      {% block main %}
      {% endblock %}
    </main>

    <footer class="footer">
      <hr/>
      {% block footer %}
      {% endblock %}
    </footer>
  </div>

  <script src="{% static 'core/jquery-3.2.1.js' %}"></script>
  <script src="{% static 'core/bootstrap-4/js/bootstrap.js' %}"></script>
</body>

</html>

core/templates/core/index.html
{% extends "core/base.html" %}
{% load i18n %}

{% block main %}
{% if user.is_authenticated %}
<div class="jumbotron">
  <h1>{% blocktrans with name=user.first_name %}Welcome {{ name }}{% endblocktrans %}</h1>
</div>
<div class="row">
  <div class="col-md-6">
    <h4>{% trans "Notifications" %}</h4>
    <ul>
      <li>{% trans "New Products in Stock" %}</li>
      <li>{% trans "Products need to be picked up" %}</li>
      <li>{% trans "This is hardcoded" %}</li>
    </ul>
  </div>
  <div class="col-md-6">
    <h4>{% trans "System Updates" %}</h4>
    <ul>
      <li>{% trans "Able to place orders to providers" %}</li>
      <li>{% trans "Sending email to renters and buyers when the order is being procesed." %}</li>
      <li>{% trans "This is hardcoded" %}</li>
    </ul>
  </div>
</div>
{% else %}
<div class="jumbotron">
  <h1>{% trans "Welcome to Tektronic" %}</h1>
  <p class="lead">
    {% trans "The place for all your IT needs." %}
  </p>
</div>
<div class="row">
  <div class="col-md-4">
    <h4>{% trans "Rentals" %}</h4>
    <p>{% trans "We have lots of items in stock that can be rented." %}</p>
  </div>
  <div class="col-md-4">
    <h4>{% trans "Purchases" %}</h4>
    <p>{% trans "Buy our Products. We have a great selection of new and used products" %}</p>
  </div>
  <div class="col-md-4">
    <h4>{% trans "Outsourcing" %}</h4>
    <p>{% trans "Have a client but don't have enough products. Partner with us" %}</p>
  </div>
</div>
{% endif %}

{% endblock %}